const express = require("express");
const app = express();
const users = require("./routes/userRouter");
const amenities = require("./routes/amenity.routes");
const amenityCategories = require("./routes/amenityCategory.routes");
const upload = require("./routes/uploadRouter");
const errorMiddleware = require("./middlewares/error");
const cookieParser = require("cookie-parser");
const logger = require("morgan");
const cors = require("cors");
app.use(cors({ credentials: true, origin: true }));
app.use(cookieParser());
app.use(logger("tiny"));
app.use(express.json());
app.use("/api", users);
app.use("/api/amenity", amenities);
app.use("/api/amenity/c", amenityCategories);
app.use("/api/upload", upload);
app.use(errorMiddleware);

module.exports = app;
